// -------------------------------------------------------------
//
// Module: firfilt
// Generated by MATLAB(R) 9.2 and the Filter Design HDL Coder 3.1.1.
// Generated on: 2018-11-01 17:25:09
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: C:\Users\user\Desktop\FPGA PROJECT
// Name: firfilt
// InputDataType: numerictype(1,16,15)
// TargetLanguage: Verilog
// TestBenchName: firfilt_tb
// TestBenchUserStimulus:  User data, length 1000

// Filter Specifications:
//
// Sample Rate            : 360 Hz
// Response               : Bandpass
// Specification          : Fst1,Fp1,Fp2,Fst2,Ast1,Ap,Ast2
// First Passband Edge    : 25 Hz
// Second Passband Edge   : 125 Hz
// Passband Ripple        : 1 dB
// Second Stopband Atten. : 60 dB
// First Stopband Atten.  : 60 dB
// Second Stopband Edge   : 150 Hz
// First Stopband Edge    : 10 Hz
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 53
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s16,15 -> [-1 1)
// -------------------------------------------------------------
// Multipliers           : 51



`timescale 1 ns / 1 ns

module firfilt
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [11:0] filter_out; //sfix12_En11

////////////////////////////////////////////////////////////////
//Module Architecture: firfilt
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000000001000111; //sfix16_En15
  parameter signed [15:0] coeff2 = 16'b0000000001010011; //sfix16_En15
  parameter signed [15:0] coeff3 = 16'b0000000010110001; //sfix16_En15
  parameter signed [15:0] coeff4 = 16'b0000000000000010; //sfix16_En15
  parameter signed [15:0] coeff5 = 16'b1111110101011111; //sfix16_En15
  parameter signed [15:0] coeff6 = 16'b1111111001101001; //sfix16_En15
  parameter signed [15:0] coeff7 = 16'b0000000010111010; //sfix16_En15
  parameter signed [15:0] coeff8 = 16'b1111111010101001; //sfix16_En15
  parameter signed [15:0] coeff9 = 16'b1111111111011110; //sfix16_En15
  parameter signed [15:0] coeff10 = 16'b0000000110110110; //sfix16_En15
  parameter signed [15:0] coeff11 = 16'b1111111101111111; //sfix16_En15
  parameter signed [15:0] coeff12 = 16'b0000001001110000; //sfix16_En15
  parameter signed [15:0] coeff13 = 16'b0000001011010101; //sfix16_En15
  parameter signed [15:0] coeff14 = 16'b0000000000010011; //sfix16_En15
  parameter signed [15:0] coeff15 = 16'b0000010001110110; //sfix16_En15
  parameter signed [15:0] coeff16 = 16'b0000000101111010; //sfix16_En15
  parameter signed [15:0] coeff17 = 16'b1111111011000110; //sfix16_En15
  parameter signed [15:0] coeff18 = 16'b0000001111001111; //sfix16_En15
  parameter signed [15:0] coeff19 = 16'b1111101110001011; //sfix16_En15
  parameter signed [15:0] coeff20 = 16'b1111101101011100; //sfix16_En15
  parameter signed [15:0] coeff21 = 16'b0000000000000110; //sfix16_En15
  parameter signed [15:0] coeff22 = 16'b1111000100001010; //sfix16_En15
  parameter signed [15:0] coeff23 = 16'b1111100101110101; //sfix16_En15
  parameter signed [15:0] coeff24 = 16'b1111101101100000; //sfix16_En15
  parameter signed [15:0] coeff25 = 16'b1101111100101011; //sfix16_En15
  parameter signed [15:0] coeff26 = 16'b0001000101000010; //sfix16_En15
  parameter signed [15:0] coeff27 = 16'b0100111010011111; //sfix16_En15
  parameter signed [15:0] coeff28 = 16'b0001000101000010; //sfix16_En15
  parameter signed [15:0] coeff29 = 16'b1101111100101011; //sfix16_En15
  parameter signed [15:0] coeff30 = 16'b1111101101100000; //sfix16_En15
  parameter signed [15:0] coeff31 = 16'b1111100101110101; //sfix16_En15
  parameter signed [15:0] coeff32 = 16'b1111000100001010; //sfix16_En15
  parameter signed [15:0] coeff33 = 16'b0000000000000110; //sfix16_En15
  parameter signed [15:0] coeff34 = 16'b1111101101011100; //sfix16_En15
  parameter signed [15:0] coeff35 = 16'b1111101110001011; //sfix16_En15
  parameter signed [15:0] coeff36 = 16'b0000001111001111; //sfix16_En15
  parameter signed [15:0] coeff37 = 16'b1111111011000110; //sfix16_En15
  parameter signed [15:0] coeff38 = 16'b0000000101111010; //sfix16_En15
  parameter signed [15:0] coeff39 = 16'b0000010001110110; //sfix16_En15
  parameter signed [15:0] coeff40 = 16'b0000000000010011; //sfix16_En15
  parameter signed [15:0] coeff41 = 16'b0000001011010101; //sfix16_En15
  parameter signed [15:0] coeff42 = 16'b0000001001110000; //sfix16_En15
  parameter signed [15:0] coeff43 = 16'b1111111101111111; //sfix16_En15
  parameter signed [15:0] coeff44 = 16'b0000000110110110; //sfix16_En15
  parameter signed [15:0] coeff45 = 16'b1111111111011110; //sfix16_En15
  parameter signed [15:0] coeff46 = 16'b1111111010101001; //sfix16_En15
  parameter signed [15:0] coeff47 = 16'b0000000010111010; //sfix16_En15
  parameter signed [15:0] coeff48 = 16'b1111111001101001; //sfix16_En15
  parameter signed [15:0] coeff49 = 16'b1111110101011111; //sfix16_En15
  parameter signed [15:0] coeff50 = 16'b0000000000000010; //sfix16_En15
  parameter signed [15:0] coeff51 = 16'b0000000010110001; //sfix16_En15
  parameter signed [15:0] coeff52 = 16'b0000000001010011; //sfix16_En15
  parameter signed [15:0] coeff53 = 16'b0000000001000111; //sfix16_En15

  // Signals
  reg  signed [15:0] delay_pipeline [0:52] ; // sfix16_En15
  wire signed [31:0] product53; // sfix32_En30
  wire signed [31:0] product52; // sfix32_En30
  wire signed [31:0] product51; // sfix32_En30
  wire signed [31:0] product50; // sfix32_En30
  wire signed [31:0] product49; // sfix32_En30
  wire signed [31:0] product48; // sfix32_En30
  wire signed [31:0] product47; // sfix32_En30
  wire signed [31:0] product46; // sfix32_En30
  wire signed [31:0] product45; // sfix32_En30
  wire signed [31:0] product44; // sfix32_En30
  wire signed [31:0] product43; // sfix32_En30
  wire signed [31:0] product42; // sfix32_En30
  wire signed [31:0] product41; // sfix32_En30
  wire signed [31:0] product40; // sfix32_En30
  wire signed [31:0] product39; // sfix32_En30
  wire signed [31:0] product38; // sfix32_En30
  wire signed [31:0] product37; // sfix32_En30
  wire signed [31:0] product36; // sfix32_En30
  wire signed [31:0] product35; // sfix32_En30
  wire signed [31:0] product34; // sfix32_En30
  wire signed [31:0] product33; // sfix32_En30
  wire signed [31:0] product32; // sfix32_En30
  wire signed [31:0] product31; // sfix32_En30
  wire signed [31:0] product30; // sfix32_En30
  wire signed [31:0] product29; // sfix32_En30
  wire signed [31:0] product28; // sfix32_En30
  wire signed [31:0] product27; // sfix32_En30
  wire signed [31:0] product26; // sfix32_En30
  wire signed [31:0] product25; // sfix32_En30
  wire signed [31:0] product24; // sfix32_En30
  wire signed [31:0] product23; // sfix32_En30
  wire signed [31:0] product22; // sfix32_En30
  wire signed [31:0] product21; // sfix32_En30
  wire signed [31:0] product20; // sfix32_En30
  wire signed [31:0] product19; // sfix32_En30
  wire signed [31:0] product18; // sfix32_En30
  wire signed [31:0] product17; // sfix32_En30
  wire signed [31:0] product16; // sfix32_En30
  wire signed [31:0] product15; // sfix32_En30
  wire signed [31:0] product14; // sfix32_En30
  wire signed [31:0] product13; // sfix32_En30
  wire signed [31:0] product12; // sfix32_En30
  wire signed [31:0] product11; // sfix32_En30
  wire signed [31:0] product10; // sfix32_En30
  wire signed [31:0] product9; // sfix32_En30
  wire signed [31:0] product8; // sfix32_En30
  wire signed [31:0] product7; // sfix32_En30
  wire signed [31:0] product6; // sfix32_En30
  wire signed [31:0] product5; // sfix32_En30
  wire signed [31:0] product4; // sfix32_En30
  wire signed [31:0] product3; // sfix32_En30
  wire signed [31:0] product2; // sfix32_En30
  wire signed [37:0] product1_cast; // sfix38_En30
  wire signed [31:0] product1; // sfix32_En30
  wire signed [37:0] sum1; // sfix38_En30
  wire signed [37:0] add_signext; // sfix38_En30
  wire signed [37:0] add_signext_1; // sfix38_En30
  wire signed [38:0] add_temp; // sfix39_En30
  wire signed [37:0] sum2; // sfix38_En30
  wire signed [37:0] add_signext_2; // sfix38_En30
  wire signed [37:0] add_signext_3; // sfix38_En30
  wire signed [38:0] add_temp_1; // sfix39_En30
  wire signed [37:0] sum3; // sfix38_En30
  wire signed [37:0] add_signext_4; // sfix38_En30
  wire signed [37:0] add_signext_5; // sfix38_En30
  wire signed [38:0] add_temp_2; // sfix39_En30
  wire signed [37:0] sum4; // sfix38_En30
  wire signed [37:0] add_signext_6; // sfix38_En30
  wire signed [37:0] add_signext_7; // sfix38_En30
  wire signed [38:0] add_temp_3; // sfix39_En30
  wire signed [37:0] sum5; // sfix38_En30
  wire signed [37:0] add_signext_8; // sfix38_En30
  wire signed [37:0] add_signext_9; // sfix38_En30
  wire signed [38:0] add_temp_4; // sfix39_En30
  wire signed [37:0] sum6; // sfix38_En30
  wire signed [37:0] add_signext_10; // sfix38_En30
  wire signed [37:0] add_signext_11; // sfix38_En30
  wire signed [38:0] add_temp_5; // sfix39_En30
  wire signed [37:0] sum7; // sfix38_En30
  wire signed [37:0] add_signext_12; // sfix38_En30
  wire signed [37:0] add_signext_13; // sfix38_En30
  wire signed [38:0] add_temp_6; // sfix39_En30
  wire signed [37:0] sum8; // sfix38_En30
  wire signed [37:0] add_signext_14; // sfix38_En30
  wire signed [37:0] add_signext_15; // sfix38_En30
  wire signed [38:0] add_temp_7; // sfix39_En30
  wire signed [37:0] sum9; // sfix38_En30
  wire signed [37:0] add_signext_16; // sfix38_En30
  wire signed [37:0] add_signext_17; // sfix38_En30
  wire signed [38:0] add_temp_8; // sfix39_En30
  wire signed [37:0] sum10; // sfix38_En30
  wire signed [37:0] add_signext_18; // sfix38_En30
  wire signed [37:0] add_signext_19; // sfix38_En30
  wire signed [38:0] add_temp_9; // sfix39_En30
  wire signed [37:0] sum11; // sfix38_En30
  wire signed [37:0] add_signext_20; // sfix38_En30
  wire signed [37:0] add_signext_21; // sfix38_En30
  wire signed [38:0] add_temp_10; // sfix39_En30
  wire signed [37:0] sum12; // sfix38_En30
  wire signed [37:0] add_signext_22; // sfix38_En30
  wire signed [37:0] add_signext_23; // sfix38_En30
  wire signed [38:0] add_temp_11; // sfix39_En30
  wire signed [37:0] sum13; // sfix38_En30
  wire signed [37:0] add_signext_24; // sfix38_En30
  wire signed [37:0] add_signext_25; // sfix38_En30
  wire signed [38:0] add_temp_12; // sfix39_En30
  wire signed [37:0] sum14; // sfix38_En30
  wire signed [37:0] add_signext_26; // sfix38_En30
  wire signed [37:0] add_signext_27; // sfix38_En30
  wire signed [38:0] add_temp_13; // sfix39_En30
  wire signed [37:0] sum15; // sfix38_En30
  wire signed [37:0] add_signext_28; // sfix38_En30
  wire signed [37:0] add_signext_29; // sfix38_En30
  wire signed [38:0] add_temp_14; // sfix39_En30
  wire signed [37:0] sum16; // sfix38_En30
  wire signed [37:0] add_signext_30; // sfix38_En30
  wire signed [37:0] add_signext_31; // sfix38_En30
  wire signed [38:0] add_temp_15; // sfix39_En30
  wire signed [37:0] sum17; // sfix38_En30
  wire signed [37:0] add_signext_32; // sfix38_En30
  wire signed [37:0] add_signext_33; // sfix38_En30
  wire signed [38:0] add_temp_16; // sfix39_En30
  wire signed [37:0] sum18; // sfix38_En30
  wire signed [37:0] add_signext_34; // sfix38_En30
  wire signed [37:0] add_signext_35; // sfix38_En30
  wire signed [38:0] add_temp_17; // sfix39_En30
  wire signed [37:0] sum19; // sfix38_En30
  wire signed [37:0] add_signext_36; // sfix38_En30
  wire signed [37:0] add_signext_37; // sfix38_En30
  wire signed [38:0] add_temp_18; // sfix39_En30
  wire signed [37:0] sum20; // sfix38_En30
  wire signed [37:0] add_signext_38; // sfix38_En30
  wire signed [37:0] add_signext_39; // sfix38_En30
  wire signed [38:0] add_temp_19; // sfix39_En30
  wire signed [37:0] sum21; // sfix38_En30
  wire signed [37:0] add_signext_40; // sfix38_En30
  wire signed [37:0] add_signext_41; // sfix38_En30
  wire signed [38:0] add_temp_20; // sfix39_En30
  wire signed [37:0] sum22; // sfix38_En30
  wire signed [37:0] add_signext_42; // sfix38_En30
  wire signed [37:0] add_signext_43; // sfix38_En30
  wire signed [38:0] add_temp_21; // sfix39_En30
  wire signed [37:0] sum23; // sfix38_En30
  wire signed [37:0] add_signext_44; // sfix38_En30
  wire signed [37:0] add_signext_45; // sfix38_En30
  wire signed [38:0] add_temp_22; // sfix39_En30
  wire signed [37:0] sum24; // sfix38_En30
  wire signed [37:0] add_signext_46; // sfix38_En30
  wire signed [37:0] add_signext_47; // sfix38_En30
  wire signed [38:0] add_temp_23; // sfix39_En30
  wire signed [37:0] sum25; // sfix38_En30
  wire signed [37:0] add_signext_48; // sfix38_En30
  wire signed [37:0] add_signext_49; // sfix38_En30
  wire signed [38:0] add_temp_24; // sfix39_En30
  wire signed [37:0] sum26; // sfix38_En30
  wire signed [37:0] add_signext_50; // sfix38_En30
  wire signed [37:0] add_signext_51; // sfix38_En30
  wire signed [38:0] add_temp_25; // sfix39_En30
  wire signed [37:0] sum27; // sfix38_En30
  wire signed [37:0] add_signext_52; // sfix38_En30
  wire signed [37:0] add_signext_53; // sfix38_En30
  wire signed [38:0] add_temp_26; // sfix39_En30
  wire signed [37:0] sum28; // sfix38_En30
  wire signed [37:0] add_signext_54; // sfix38_En30
  wire signed [37:0] add_signext_55; // sfix38_En30
  wire signed [38:0] add_temp_27; // sfix39_En30
  wire signed [37:0] sum29; // sfix38_En30
  wire signed [37:0] add_signext_56; // sfix38_En30
  wire signed [37:0] add_signext_57; // sfix38_En30
  wire signed [38:0] add_temp_28; // sfix39_En30
  wire signed [37:0] sum30; // sfix38_En30
  wire signed [37:0] add_signext_58; // sfix38_En30
  wire signed [37:0] add_signext_59; // sfix38_En30
  wire signed [38:0] add_temp_29; // sfix39_En30
  wire signed [37:0] sum31; // sfix38_En30
  wire signed [37:0] add_signext_60; // sfix38_En30
  wire signed [37:0] add_signext_61; // sfix38_En30
  wire signed [38:0] add_temp_30; // sfix39_En30
  wire signed [37:0] sum32; // sfix38_En30
  wire signed [37:0] add_signext_62; // sfix38_En30
  wire signed [37:0] add_signext_63; // sfix38_En30
  wire signed [38:0] add_temp_31; // sfix39_En30
  wire signed [37:0] sum33; // sfix38_En30
  wire signed [37:0] add_signext_64; // sfix38_En30
  wire signed [37:0] add_signext_65; // sfix38_En30
  wire signed [38:0] add_temp_32; // sfix39_En30
  wire signed [37:0] sum34; // sfix38_En30
  wire signed [37:0] add_signext_66; // sfix38_En30
  wire signed [37:0] add_signext_67; // sfix38_En30
  wire signed [38:0] add_temp_33; // sfix39_En30
  wire signed [37:0] sum35; // sfix38_En30
  wire signed [37:0] add_signext_68; // sfix38_En30
  wire signed [37:0] add_signext_69; // sfix38_En30
  wire signed [38:0] add_temp_34; // sfix39_En30
  wire signed [37:0] sum36; // sfix38_En30
  wire signed [37:0] add_signext_70; // sfix38_En30
  wire signed [37:0] add_signext_71; // sfix38_En30
  wire signed [38:0] add_temp_35; // sfix39_En30
  wire signed [37:0] sum37; // sfix38_En30
  wire signed [37:0] add_signext_72; // sfix38_En30
  wire signed [37:0] add_signext_73; // sfix38_En30
  wire signed [38:0] add_temp_36; // sfix39_En30
  wire signed [37:0] sum38; // sfix38_En30
  wire signed [37:0] add_signext_74; // sfix38_En30
  wire signed [37:0] add_signext_75; // sfix38_En30
  wire signed [38:0] add_temp_37; // sfix39_En30
  wire signed [37:0] sum39; // sfix38_En30
  wire signed [37:0] add_signext_76; // sfix38_En30
  wire signed [37:0] add_signext_77; // sfix38_En30
  wire signed [38:0] add_temp_38; // sfix39_En30
  wire signed [37:0] sum40; // sfix38_En30
  wire signed [37:0] add_signext_78; // sfix38_En30
  wire signed [37:0] add_signext_79; // sfix38_En30
  wire signed [38:0] add_temp_39; // sfix39_En30
  wire signed [37:0] sum41; // sfix38_En30
  wire signed [37:0] add_signext_80; // sfix38_En30
  wire signed [37:0] add_signext_81; // sfix38_En30
  wire signed [38:0] add_temp_40; // sfix39_En30
  wire signed [37:0] sum42; // sfix38_En30
  wire signed [37:0] add_signext_82; // sfix38_En30
  wire signed [37:0] add_signext_83; // sfix38_En30
  wire signed [38:0] add_temp_41; // sfix39_En30
  wire signed [37:0] sum43; // sfix38_En30
  wire signed [37:0] add_signext_84; // sfix38_En30
  wire signed [37:0] add_signext_85; // sfix38_En30
  wire signed [38:0] add_temp_42; // sfix39_En30
  wire signed [37:0] sum44; // sfix38_En30
  wire signed [37:0] add_signext_86; // sfix38_En30
  wire signed [37:0] add_signext_87; // sfix38_En30
  wire signed [38:0] add_temp_43; // sfix39_En30
  wire signed [37:0] sum45; // sfix38_En30
  wire signed [37:0] add_signext_88; // sfix38_En30
  wire signed [37:0] add_signext_89; // sfix38_En30
  wire signed [38:0] add_temp_44; // sfix39_En30
  wire signed [37:0] sum46; // sfix38_En30
  wire signed [37:0] add_signext_90; // sfix38_En30
  wire signed [37:0] add_signext_91; // sfix38_En30
  wire signed [38:0] add_temp_45; // sfix39_En30
  wire signed [37:0] sum47; // sfix38_En30
  wire signed [37:0] add_signext_92; // sfix38_En30
  wire signed [37:0] add_signext_93; // sfix38_En30
  wire signed [38:0] add_temp_46; // sfix39_En30
  wire signed [37:0] sum48; // sfix38_En30
  wire signed [37:0] add_signext_94; // sfix38_En30
  wire signed [37:0] add_signext_95; // sfix38_En30
  wire signed [38:0] add_temp_47; // sfix39_En30
  wire signed [37:0] sum49; // sfix38_En30
  wire signed [37:0] add_signext_96; // sfix38_En30
  wire signed [37:0] add_signext_97; // sfix38_En30
  wire signed [38:0] add_temp_48; // sfix39_En30
  wire signed [37:0] sum50; // sfix38_En30
  wire signed [37:0] add_signext_98; // sfix38_En30
  wire signed [37:0] add_signext_99; // sfix38_En30
  wire signed [38:0] add_temp_49; // sfix39_En30
  wire signed [37:0] sum51; // sfix38_En30
  wire signed [37:0] add_signext_100; // sfix38_En30
  wire signed [37:0] add_signext_101; // sfix38_En30
  wire signed [38:0] add_temp_50; // sfix39_En30
  wire signed [37:0] sum52; // sfix38_En30
  wire signed [37:0] add_signext_102; // sfix38_En30
  wire signed [37:0] add_signext_103; // sfix38_En30
  wire signed [38:0] add_temp_51; // sfix39_En30
  wire signed [11:0] output_typeconvert; // sfix12_En11
  reg  signed [11:0] output_register; // sfix12_En11

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
        delay_pipeline[51] <= 0;
        delay_pipeline[52] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
          delay_pipeline[51] <= delay_pipeline[50];
          delay_pipeline[52] <= delay_pipeline[51];
        end
      end
    end // Delay_Pipeline_process


  assign product53 = delay_pipeline[52] * coeff53;

  assign product52 = delay_pipeline[51] * coeff52;

  assign product51 = delay_pipeline[50] * coeff51;

  assign product50 = $signed({delay_pipeline[49][15:0], 1'b0});

  assign product49 = delay_pipeline[48] * coeff49;

  assign product48 = delay_pipeline[47] * coeff48;

  assign product47 = delay_pipeline[46] * coeff47;

  assign product46 = delay_pipeline[45] * coeff46;

  assign product45 = delay_pipeline[44] * coeff45;

  assign product44 = delay_pipeline[43] * coeff44;

  assign product43 = delay_pipeline[42] * coeff43;

  assign product42 = delay_pipeline[41] * coeff42;

  assign product41 = delay_pipeline[40] * coeff41;

  assign product40 = delay_pipeline[39] * coeff40;

  assign product39 = delay_pipeline[38] * coeff39;

  assign product38 = delay_pipeline[37] * coeff38;

  assign product37 = delay_pipeline[36] * coeff37;

  assign product36 = delay_pipeline[35] * coeff36;

  assign product35 = delay_pipeline[34] * coeff35;

  assign product34 = delay_pipeline[33] * coeff34;

  assign product33 = delay_pipeline[32] * coeff33;

  assign product32 = delay_pipeline[31] * coeff32;

  assign product31 = delay_pipeline[30] * coeff31;

  assign product30 = delay_pipeline[29] * coeff30;

  assign product29 = delay_pipeline[28] * coeff29;

  assign product28 = delay_pipeline[27] * coeff28;

  assign product27 = delay_pipeline[26] * coeff27;

  assign product26 = delay_pipeline[25] * coeff26;

  assign product25 = delay_pipeline[24] * coeff25;

  assign product24 = delay_pipeline[23] * coeff24;

  assign product23 = delay_pipeline[22] * coeff23;

  assign product22 = delay_pipeline[21] * coeff22;

  assign product21 = delay_pipeline[20] * coeff21;

  assign product20 = delay_pipeline[19] * coeff20;

  assign product19 = delay_pipeline[18] * coeff19;

  assign product18 = delay_pipeline[17] * coeff18;

  assign product17 = delay_pipeline[16] * coeff17;

  assign product16 = delay_pipeline[15] * coeff16;

  assign product15 = delay_pipeline[14] * coeff15;

  assign product14 = delay_pipeline[13] * coeff14;

  assign product13 = delay_pipeline[12] * coeff13;

  assign product12 = delay_pipeline[11] * coeff12;

  assign product11 = delay_pipeline[10] * coeff11;

  assign product10 = delay_pipeline[9] * coeff10;

  assign product9 = delay_pipeline[8] * coeff9;

  assign product8 = delay_pipeline[7] * coeff8;

  assign product7 = delay_pipeline[6] * coeff7;

  assign product6 = delay_pipeline[5] * coeff6;

  assign product5 = delay_pipeline[4] * coeff5;

  assign product4 = $signed({delay_pipeline[3][15:0], 1'b0});

  assign product3 = delay_pipeline[2] * coeff3;

  assign product2 = delay_pipeline[1] * coeff2;

  assign product1_cast = $signed({{6{product1[31]}}, product1});

  assign product1 = delay_pipeline[0] * coeff1;

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{6{product2[31]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[37:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{6{product3[31]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[37:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{6{product4[31]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[37:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{6{product5[31]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[37:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{6{product6[31]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[37:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{6{product7[31]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[37:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{6{product8[31]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[37:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{6{product9[31]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[37:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{6{product10[31]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[37:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{6{product11[31]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[37:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{6{product12[31]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[37:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{6{product13[31]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[37:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{6{product14[31]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[37:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{6{product15[31]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[37:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{6{product16[31]}}, product16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[37:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{6{product17[31]}}, product17});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[37:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{6{product18[31]}}, product18});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[37:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{6{product19[31]}}, product19});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[37:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{6{product20[31]}}, product20});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[37:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{6{product21[31]}}, product21});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[37:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{6{product22[31]}}, product22});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[37:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{6{product23[31]}}, product23});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[37:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{6{product24[31]}}, product24});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[37:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{6{product25[31]}}, product25});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[37:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{6{product26[31]}}, product26});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[37:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{6{product27[31]}}, product27});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[37:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{6{product28[31]}}, product28});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[37:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{6{product29[31]}}, product29});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[37:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{6{product30[31]}}, product30});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[37:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{6{product31[31]}}, product31});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[37:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{6{product32[31]}}, product32});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = add_temp_30[37:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{6{product33[31]}}, product33});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = add_temp_31[37:0];

  assign add_signext_64 = sum32;
  assign add_signext_65 = $signed({{6{product34[31]}}, product34});
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum33 = add_temp_32[37:0];

  assign add_signext_66 = sum33;
  assign add_signext_67 = $signed({{6{product35[31]}}, product35});
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum34 = add_temp_33[37:0];

  assign add_signext_68 = sum34;
  assign add_signext_69 = $signed({{6{product36[31]}}, product36});
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum35 = add_temp_34[37:0];

  assign add_signext_70 = sum35;
  assign add_signext_71 = $signed({{6{product37[31]}}, product37});
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum36 = add_temp_35[37:0];

  assign add_signext_72 = sum36;
  assign add_signext_73 = $signed({{6{product38[31]}}, product38});
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum37 = add_temp_36[37:0];

  assign add_signext_74 = sum37;
  assign add_signext_75 = $signed({{6{product39[31]}}, product39});
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum38 = add_temp_37[37:0];

  assign add_signext_76 = sum38;
  assign add_signext_77 = $signed({{6{product40[31]}}, product40});
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum39 = add_temp_38[37:0];

  assign add_signext_78 = sum39;
  assign add_signext_79 = $signed({{6{product41[31]}}, product41});
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum40 = add_temp_39[37:0];

  assign add_signext_80 = sum40;
  assign add_signext_81 = $signed({{6{product42[31]}}, product42});
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum41 = add_temp_40[37:0];

  assign add_signext_82 = sum41;
  assign add_signext_83 = $signed({{6{product43[31]}}, product43});
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum42 = add_temp_41[37:0];

  assign add_signext_84 = sum42;
  assign add_signext_85 = $signed({{6{product44[31]}}, product44});
  assign add_temp_42 = add_signext_84 + add_signext_85;
  assign sum43 = add_temp_42[37:0];

  assign add_signext_86 = sum43;
  assign add_signext_87 = $signed({{6{product45[31]}}, product45});
  assign add_temp_43 = add_signext_86 + add_signext_87;
  assign sum44 = add_temp_43[37:0];

  assign add_signext_88 = sum44;
  assign add_signext_89 = $signed({{6{product46[31]}}, product46});
  assign add_temp_44 = add_signext_88 + add_signext_89;
  assign sum45 = add_temp_44[37:0];

  assign add_signext_90 = sum45;
  assign add_signext_91 = $signed({{6{product47[31]}}, product47});
  assign add_temp_45 = add_signext_90 + add_signext_91;
  assign sum46 = add_temp_45[37:0];

  assign add_signext_92 = sum46;
  assign add_signext_93 = $signed({{6{product48[31]}}, product48});
  assign add_temp_46 = add_signext_92 + add_signext_93;
  assign sum47 = add_temp_46[37:0];

  assign add_signext_94 = sum47;
  assign add_signext_95 = $signed({{6{product49[31]}}, product49});
  assign add_temp_47 = add_signext_94 + add_signext_95;
  assign sum48 = add_temp_47[37:0];

  assign add_signext_96 = sum48;
  assign add_signext_97 = $signed({{6{product50[31]}}, product50});
  assign add_temp_48 = add_signext_96 + add_signext_97;
  assign sum49 = add_temp_48[37:0];

  assign add_signext_98 = sum49;
  assign add_signext_99 = $signed({{6{product51[31]}}, product51});
  assign add_temp_49 = add_signext_98 + add_signext_99;
  assign sum50 = add_temp_49[37:0];

  assign add_signext_100 = sum50;
  assign add_signext_101 = $signed({{6{product52[31]}}, product52});
  assign add_temp_50 = add_signext_100 + add_signext_101;
  assign sum51 = add_temp_50[37:0];

  assign add_signext_102 = sum51;
  assign add_signext_103 = $signed({{6{product53[31]}}, product53});
  assign add_temp_51 = add_signext_102 + add_signext_103;
  assign sum52 = add_temp_51[37:0];

  assign output_typeconvert = sum52[30:19];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // firfilt
